name: Sync to Lab Repository

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      # Bước này sẽ nạp code và tự động dùng Token của bạn để xác thực mọi quyền
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.LAB_GITHUB_TOKEN }} 

      - name: Push to Lab Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Thêm đường dẫn của PIISAlab (Lúc này không cần nhét Token vào URL nữa vì đã cấp ở trên)
          git remote add lab https://github.com/PIISAlab/Design-and-implementation-of-a-vision-enhancement-system-on-the-FPGA-DE1-SoC-platform-.git

        
          # Đẩy nhánh main sang Lab
          git push lab main --force
